steps:
  # 1. Pull the latest image to use as a cache source
  # We allow this step to fail if the image doesn't exist yet (e.g., first build)
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args: ["-c", "docker pull gcr.io/$PROJECT_ID/backend:latest || exit 0"]

  # 2. Build the container image, using the pulled image as a cache
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "gcr.io/$PROJECT_ID/backend:latest"
      - "--cache-from"
      - "gcr.io/$PROJECT_ID/backend:latest"
      - "-f"
      - "Dockerfile.prod"
      - "."

  # 3. Push the new container image to the registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/backend:latest"]

# Tag the image as 'latest'
images:
  - "gcr.io/$PROJECT_ID/backend:latest"
