services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    develop:
      watch:
        - action: sync
          path: ./
          target: /app
          ignore:
            - .git
            - tmp
        - action: rebuild
          path : package.json
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: pgvector/pgvector:pg16
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: